project:
  type: website
  output-dir: docs

website:
  title: "PPE Econometrics 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Handouts/index.qmd
        text: Handouts
      - href: Labs/index.qmd
        text: Labs
      - href: Exams/index.qmd
        text: Exams
      - href: Data/index.qmd
        text: Data

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    title-block-banner: true
